"""modified all tables

Revision ID: 0ede851bdd92
Revises: a286c996e4e6
Create Date: 2025-07-22 09:36:52.070189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ede851bdd92'
down_revision: Union[str, Sequence[str], None] = 'a286c996e4e6'
branch_labels: Union[str, Sequence[str], None] = ('second modification of tables',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('images_path', sa.String(length=255), nullable=False))
    op.drop_column('images', 'images')
    op.add_column('statuses', sa.Column('sequence', sa.Integer(), nullable=False))
    op.drop_column('statuses', 'number')
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_profile_key'), 'users', type_='unique')
    op.create_unique_constraint('uq_user_phone_country', 'users', ['phone', 'country'])
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_phone_country', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_profile_key'), 'users', ['profile'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.add_column('statuses', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('statuses', 'sequence')
    op.add_column('images', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('images', 'images_path')
    # ### end Alembic commands ###
