"""First migration(2nd tho)

Revision ID: 33d84615292e
Revises: 
Create Date: 2025-09-12 17:47:33.070668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d84615292e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('main_folder_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('main_folder_id'),
    sa.UniqueConstraint('phone', 'country', name='uq_user_phone_country')
    )
    op.create_table('statuses',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('write_up', sa.String(), nullable=True),
    sa.Column('is_upload', sa.Boolean(), nullable=False),
    sa.Column('is_text', sa.Boolean(), nullable=False),
    sa.Column('images_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('schedule', sa.String(length=20), nullable=False),
    sa.Column('schedule_time', sa.Time(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statuses_user_id'), 'statuses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statuses_user_id'), table_name='statuses')
    op.drop_table('statuses')
    op.drop_table('users')
    # ### end Alembic commands ###
