"""add default schedule and time to status table

Revision ID: 3f7959307e36
Revises: a41ab9fa789c
Create Date: 2025-07-25 04:23:29.453867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7959307e36'
down_revision: Union[str, Sequence[str], None] = 'a41ab9fa789c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statuses', sa.Column('schedule', sa.String(length=20), nullable=False))
    op.add_column('statuses', sa.Column('time', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'time')
    op.drop_column('statuses', 'schedule')
    # ### end Alembic commands ###
