"""add link code to userdb

Revision ID: 6ba059deb924
Revises: 6ff58c11b4a7
Create Date: 2025-11-04 22:08:24.030905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba059deb924'
down_revision: Union[str, Sequence[str], None] = '6ff58c11b4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('link_code', sa.String(length=9), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'link_code')
    # ### end Alembic commands ###
