"""removed image  table

Revision ID: 7829ede6c420
Revises: 0ede851bdd92
Create Date: 2025-07-22 10:31:58.356928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7829ede6c420'
down_revision: Union[str, Sequence[str], None] = '0ede851bdd92'
branch_labels: Union[str, Sequence[str], None] = ('removal of image table',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_status_id'), table_name='images')
    op.drop_table('images')
    op.add_column('statuses', sa.Column('images_path', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'images_path')
    op.create_table('images',
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('images_path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('images_status_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('images_pkey'))
    )
    op.create_index(op.f('ix_images_status_id'), 'images', ['status_id'], unique=False)
    # ### end Alembic commands ###
